name: PC TEST
favicon: null
layout_spectrum: 0.90479
typography_spectrum: 0.44969
title: Dogs Know Best
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#c9c0c3'
    - '#4c4a4b'
    - '#8f7c6e'
    - '#ba6a08'
  brandStrength: 0.25
  lightness: 0.46363191376440227
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
