name: PC TEST
favicon: null
layout_spectrum: 0.1871933660004288
typography_spectrum: 0.49433168419636786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8297241900581867
  lightness: 0.46363191376440227
  saturation: 0.015276441583409905
  rhythmicContrast: 0.2319620093330741
purpose: []
