name: Chagi-ya
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54677
title: Dog Knows Best
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#c9c0c3'
    - '#4c4a4b'
    - '#8f7c6e'
    - '#ba6a08'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
