name: Chagi-ya
favicon: null
layout_spectrum: 0.97003
typography_spectrum: 0.44969
title: Dogs Know Best
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#c9c0c3'
    - '#4c4a4b'
    - '#8f7c6e'
    - '#ba6a08'
  brandStrength: 0
  lightness: 0.6851064
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
